### ISSUE TITLE
Switch Viper dependency to spf13/Viper

### ISSUE THREAD

**Issue by vladimirvivien** [akutz/gofig#10]
Adding this as TODO marker issue to switch to spf13/viper to include https://github.com/spf13/viper/commit/7fb2782df3d83e0036cc89f461ed0422628776f4

**Comment by vladimirvivien** [comment]
@akutz any chance we can get this pointing to a spf13/viper or akutz/viper with a go-toml dependency?  So we can emccode/ligstorage to point to the proper dependency tree to include go-toml for kubernetes.  I know right now gofig is using akutz/viper, anything I can do there to help move this along?

**Comment by akutz** [comment]
Hi @vladimirvivien,

I am looking at this today, thanks!
